# Lab9B: 2D Numpy Array (12 points)

In [1]:
import numpy as np

## Task 1: create a 2D numpy array from a nested list and do some operations (6 points)

In [2]:
A_list = [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18],
          [19, 20, 21]]
A_list

[[10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]]

In [4]:
#your code to creat a numpuy array A from A_list, and set data type (dtype) to float32
#(0.5 point)
A = np.array(A_list, dtype="float32")

In [5]:
A

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.]], dtype=float32)

In [6]:
#your code to show the shape
A.shape

(4, 3)

In [7]:
#your code to show the type
type(A)

numpy.ndarray

In [8]:
A

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.]], dtype=float32)

### (1.1) get a row of A, using A[n,:]  (0.5 point)

In [8]:
#get the second row of A using nonnegative indexing


array([13., 14., 15.], dtype=float32)

In [9]:
#get the second row of A using negative indexing


array([13., 14., 15.], dtype=float32)

In [10]:
A

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.]], dtype=float32)

### (1.2) get a column of A, using A[:,n]   (0.5 point)

In [9]:
#get the third column of A using nonegative indexing
A[0:,2]

array([12., 15., 18., 21.], dtype=float32)

In [18]:
#get the third column of A using negative indexing
A[-4:,-1]

array([12., 15., 18., 21.], dtype=float32)

In [11]:
A

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.]], dtype=float32)

### (1.3) get a sub-array of A by array slicing, using A[a:b, c:d]   (0.5 point)

In [24]:
# get a sub-array of A using nonegative indexing
A[1:4, 1:3]


array([[14., 15.],
       [17., 18.],
       [20., 21.]], dtype=float32)

In [31]:
# get a sub-array of A using negative indexing
A[-3:,-2:]

array([[14., 15.],
       [17., 18.],
       [20., 21.]], dtype=float32)

In [16]:
A

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.]], dtype=float32)

### (1.4) get a sub-array of A    (0.5 point)

In [33]:
#one line of code:
A[[0, 2], :][:, [0, 2]]


array([[10., 12.],
       [16., 18.]], dtype=float32)

### (1.5) get maximum, minimum, average, standard deviation of each row in A    (0.5 point)
```
use the array methods: you can get a list of the methods by using dir(A) 
do NOT use for/while loop
```

In [34]:
#your code to get maximum of each row
np.max(A, axis=1)


array([12., 15., 18., 21.], dtype=float32)

In [35]:
#your code to get minimum of each row
np.min(A, axis=1)

array([10., 13., 16., 19.], dtype=float32)

In [36]:
#your code to get average of each row
np.mean(A, axis=1)

array([11., 14., 17., 20.], dtype=float32)

In [37]:
#your code to get standard deviation of each row
np.std(A, axis=1)

array([0.8164966, 0.8164966, 0.8164966, 0.8164966], dtype=float32)

In [38]:
A

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.]], dtype=float32)

### (1.6) get the average value of the elements in each row of A, and store the result in a 1D array   (1 point)
```
method 1: use a for loop
method 2: use numpy array method: mean(axis=0 or 1)
```

In [46]:
##your code for method 1

row_mean = []
for row in A:
    row_mean.append(np.mean(row))
row_mean = np.array(row_mean)

#show it here
row_mean

array([11., 14., 17., 20.], dtype=float32)

In [42]:
##your code for method 2
A.mean(axis=1)

array([11., 14., 17., 20.], dtype=float32)

In [25]:
A

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.]], dtype=float32)

### (1.7) get the average value of the elements in each row of A, and store the result in a 2D array   (0.5 point)
```
use numpy array method: mean(axis=0 or 1, keepdims=True or False)
```

In [47]:
#your code
A.mean(axis=1, keepdims=True)


array([[11.],
       [14.],
       [17.],
       [20.]], dtype=float32)

In [27]:
A

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.]], dtype=float32)

### (1.8) get the average value of the elements in each column of A, and store the result in a 1D array   (1 point)
```
method 1: use a for loop
method 2: use numpy array method: mean(axis=0 or 1) 
```

In [54]:
##your code for method 1
col_mean = []
for j in range(A.shape[1]):
    col_mean.append(np.mean(A[:,j]))
col_mean = np.array(col_mean)


#show it here
col_mean

array([14.5, 15.5, 16.5], dtype=float32)

In [55]:
##your code for method 2
A.mean(axis=0)

array([14.5, 15.5, 16.5], dtype=float32)

In [56]:
A

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.]], dtype=float32)

### (1.9) get the average value of the elements in each column of A, and store the result in a 2D array   (0.5 point)
```
numpy array method: mean(axis=0 or 1, keepdims=True or False) 
```

In [62]:
#your code
A.mean(axis=0, keepdims=True)

array([[14.5, 15.5, 16.5]], dtype=float32)

## Task-2: calculate the euclidean distance between two points in 3D (6 points)

In [68]:
P = np.array([[0, 0, 0],
              [1, 0, 0],
              [0, 1, 0],
              [1, 1, 0],
              [0, 0, 1],
              [1, 0, 1],
              [0, 1, 1],
              [1, 1, 1]],
             dtype='float32')

In [71]:
#point-0 in P
P[0] # the same as P[0,:]


array([0., 0., 0.], dtype=float32)

In [72]:
for n in range(0, P.shape[0]):
    print('point-'+str(n)+' in P is', P[n])

point-0 in P is [0. 0. 0.]
point-1 in P is [1. 0. 0.]
point-2 in P is [0. 1. 0.]
point-3 in P is [1. 1. 0.]
point-4 in P is [0. 0. 1.]
point-5 in P is [1. 0. 1.]
point-6 in P is [0. 1. 1.]
point-7 in P is [1. 1. 1.]


In [73]:
#define a new point p_new
p_new = np.array([2, 2, 2], dtype='float32')
p_new

array([2., 2., 2.], dtype=float32)

calculate the distance between p_new and P[n], n is from 0 to 7 \
store the result in an array `dist` \
dist[n] is the distance between p_new and P[n]

In [75]:
#use a for loop to get dist
#your code
dist = np.zeros(len(P), dtype='float32')  # boş dizi hazırla

for n in range(len(P)):
    dist[n] = np.linalg.norm(p_new - P[n])

In [76]:
dist

array([3.4641016, 3.       , 3.       , 2.4494898, 3.       , 2.4494898,
       2.4494898, 1.7320508], dtype=float32)

In [77]:
#one line of code using np.sqrt and np.sum to get dist
#your code
dist = np.sqrt(np.sum((P - p_new)**2, axis=1))

In [78]:
dist

array([3.4641016, 3.       , 3.       , 2.4494898, 3.       , 2.4494898,
       2.4494898, 1.7320508], dtype=float32)